### ISSUE TITLE
audit eslint / prettier configs - not catching uninitialized class members

### ISSUE THREAD

**Issue by cprice404** [momentohq/client-sdk-javascript#116]
Check and make sure that the eslint/prettier configs are up to date with what we've been using internally.

In particular - I noticed that if I was writing a class that had some private readonly member variables, and those variables were not initialized in the constructor, I didn't get a build/lint error.  In our CDK repos I believe we would catch that at compile time.

**Comment by cprice404** [comment]
task here would be to compare the eslint and prettier configs in both the example dir and the root dir with the ones from our cdk projects, such as:

https://github.com/momentohq/cacheadmin-v2/tree/main/infrastructure/aws

and

https://www.notion.so/momentohq/All-Things-TypeScript-e350a4ee90874a2e84ab1f4169f4b998#8643773be2794656848a52420f4f1c94

And make sure nothing is terribly out of sync between them.  Possibly also test the specific scenario described above and see if I am just misremembering or if there is an eslint setting that catches the case where you have an uninitialized readonly member var.

**Comment by schwern** [comment]
.eslintrc.json and .prettierrc.json match what is in cacheadmin-v2 and notion.

**Comment by schwern** [comment]
@cprice404 This appears to be a typescript thing governed by [`noUnusedLocals`](https://www.typescriptlang.org/tsconfig#noUnusedLocals).

[We have turned it off](https://github.com/search?p=1&q=org%3Amomentohq+noUnusedLocals&type=Code) everywhere but [momentohq/serverless-api-demo/infra/aws/tsconfig.json](https://github.com/momentohq/serverless-api-demo/blob/a07236239876dd781d209ca588c7b76ead233fdd/infra/aws/tsconfig.json).

Turning it on in client-sdk-javascript reveals a couple issues.

```
src/errors/errors.ts:58:20 - error TS6133: '_stack' is declared but its value is never read.

58   private readonly _stack: string | undefined;
                      ~~~~~~

src/simple-cache-client.ts:49:20 - error TS6133: 'logger' is declared but its value is never read.

49   private readonly logger: Logger;
                      ~~~~~~
```

@bruuuuuuuce @eaddingtonwhite Do you know why noUnusedLocals is off?

**Comment by schwern** [comment]
[es-lint does have `no-unused-private-class-members`](https://eslint.org/docs/latest/rules/no-unused-private-class-members#no-unused-private-class-members) but this [does not work with the `private` keyword](https://github.com/typescript-eslint/typescript-eslint/issues/4571).

**Comment by cprice404** [comment]
okay.  Thanks for looking into it @schwern .  I think we can just put this on the backburner for now.
