### ISSUE TITLE
update loadgen to match .net

### ISSUE THREAD

**Issue by cprice404** [momentohq/client-sdk-javascript#123]
Specifically, copy over the pattern for client-based rate limiting, and also implement Ellery's suggestions from this ticket:

https://github.com/momentohq/client-sdk-dotnet/issues/229

Sync up with the .net configuration, plus add a run duration.

- [x] printStatsEveryNRequests
  - Using the existing hard coded default of 1000.
- [x] cacheItemPayloadBytes: 100
- [x] numberOfConcurrentRequests: 50
- [x] maxRequestsPerSecond: 100
- [x] totalNumberOfOperationsToExecute: 500_000
- [x] run duration

**Comment by cprice404** [comment]
for getting started:

If you don't already have a tool for managing node versions, I recommend `nodenv`.  You can find some info about it in Notion.

Next we'll need to decide what environment we want to have you target when you are playing with this load generator.  I think we can probably give you a token for my dev cell, that may be a less noisy place to test rather than in alpha.

The README in the examples dir should hopefully have enough info to get you ramped on how to run the load generator.


As for the tasks for this ticket:

1. In its current incarnation the configuration for the load generator only allows you to specify the max number of concurrent requests.  It doesn't give you a way to specify the max requests per second, which is important in terms of making sure we control the load we're putting on the server.  We will want to do something like what we did in .NET to rate-limit on the client side:

https://github.com/momentohq/client-sdk-dotnet/blob/main/examples/MomentoLoadGen/Program.cs#L230-L235

without that, everyone who tries to run this for the first time just ends up getting throttled, which is very confusing :)

2. The duration of the run is currently controlled by this variable: https://github.com/momentohq/client-sdk-dotnet/blob/main/examples/MomentoLoadGen/Program.cs#L446

That is also confusing.  It would be much more intuitive to just allow them to specify a desired run duration.

**Comment by schwern** [comment]
@cprice404 load-gen spews a tremendous amount of errors obscuring any normal output and caused alerts.

```
[1671067063359] ERROR (load-gen/56457 on Windhund.local): Caught RESOURCE_EXHAUSTED error; swallowing: LimitExceededError, 8 RESOURCE_EXHAUSTED: Api Rate exceeded. Please contact support@momentohq.com for a limit increase
```

**Comment by schwern** [comment]
@cprice404 I guess that's the confusing throttling you were talking about.

**Comment by schwern** [comment]
@cprice404 Do we want to remove `totalNumberOfOperationsToExecute` and replace it with a run duration? Or keep both and stop when either is true?

**Comment by schwern** [comment]
@cprice404 What's a good default run duration?

**Comment by cprice404** [comment]
> @cprice404 I guess that's the confusing throttling you were talking about.

yep!

> @cprice404 Do we want to remove `totalNumberOfOperationsToExecute` and replace it with a run duration? Or keep both and stop when either is true?

Let's get rid of that setting I think.  I think it's just a confusing UX and the duration will make much more sense to people.  WDYT?

> @cprice404 What's a good default run duration?

1 or 2 minutes would be my first suggestion.

**Comment by schwern** [comment]
@cprice404 I talked with @rlinehan about it and it seems total duration is the thing to do and total requests (transactions?) is less useful. "My users make N tps and I want to test that for an hour".

**Comment by schwern** [comment]
@cprice404 Does this mean `printStatsEveryNRequests` should be changed to `printStatsEveryNMs`?

**Comment by cprice404** [comment]
> @cprice404 I talked with @rlinehan about it and it seems total duration is the thing to do and total requests (transactions?) is less useful. "My users make N tps and I want to test that for an hour".

exactly



> @cprice404 Does this mean `printStatsEveryNRequests` should be changed to `printStatsEveryNMs`?

yep!
