### ISSUE TITLE
Neither setContrainsElement nor setContrainsElements exist in the sdk

### ISSUE THREAD

**Issue by dobeerman** [momentohq/client-sdk-javascript#1341]
Just double-checked the SDK. The following methods are mentioned in the documentation but are not actually implemented.

1. Property `setContainsElement` does not exist on type`CacheClient`
2. Property `setContainsElements` does not exist on type `CacheClient`

Am I missed something? :thinking:

**Comment by dobeerman** [comment]
omg, I've miossed the matrix https://docs.momentohq.com/cache/develop/api-reference/language-support

Any plans to implement it? 
Anyway, we can do it by ourselves :wink:

**Comment by malandis** [comment]
@dobeerman we have added `setContainsElement` and `setContainsElements` per your request. Please try it out in v1.92.0. Let me know if you have any other concerns or questions.
