### ISSUE TITLE
Token Vending Example - Issue with Deploy

### ISSUE THREAD

**Issue by recursivecodes** [momentohq/client-sdk-javascript#1398]
I've noticed that if you try to deploy this example while you are logged in to ECR, you'll receive an error `403 Forbidden`. You might want to include a note about this in your `README`.

[Reference](https://docs.aws.amazon.com/AmazonECR/latest/public/public-registries.html#public-registry-auth)

Solution:

<img width="971" alt="image" src="https://github.com/user-attachments/assets/644ada96-17fe-4760-9766-2365b8224ce0">

**Comment by cprice404** [comment]
Thanks for the report! we will check it out.
