### ISSUE TITLE
Expose MomentoErrorCode() in the Error Responses

### ISSUE THREAD

**Issue by virratanasangpunth** [momentohq/client-sdk-javascript#168]

**Comment by virratanasangpunth** [comment]
In the dot-net sdk I see a useful method here to expose the Momento ErrorCode: https://github.com/momentohq/client-sdk-dotnet-incubating/blob/main/src/Momento.Sdk.Incubating/Responses/CacheSetAddElementsResponse.cs#L23

Many of the Response::Error classes we have in the js-sdk do not have this method exposed. We should consider exposing this.

**Comment by schwern** [comment]
#193 will make this much easier.

**Comment by schwern** [comment]
@virratanasangpunth We already do this as [errorCode()](https://github.com/momentohq/client-sdk-javascript/blob/698b31e21b7d05073f803a8e689e4b828813d697/src/messages/responses/response-base.ts#L27).

I'm going to close this. Reopen if you think they're not equivalent.

JS.

```
  public errorCode(): MomentoErrorCode {
    return this._innerException.errorCode();
  }
```

DotNet.

```
        public MomentoErrorCode ErrorCode
        {
            get => _error.ErrorCode;
        }
```
