### ISSUE TITLE
Integration tests fail in GitHub Actions

### ISSUE THREAD

**Issue by rlinehan** [momentohq/client-sdk-javascript#49]
Our integration tests are currently failing with GitHub Actions but we can't reproduce it locally. It looks like there's an issue with it contacting control plane; it seems like the socket gets closed before it can get headers back and we're never seeing the requests in the control plane logs.

We tried:
- running locally with the exact same token (succeeds, this is the only time we see customer id `github-integration` in the control plane access logs)
- running with just a README change from main (but it hasn't actually run successfully in 2 months)
- upgrading to Node version 16
- running with a Mac OS GitHub Actions runner
- someone locally running on a non-M1 Mac (still worked locally)
- commenting out all but one test that just creates a cache (that is what fails, seems like requests to MR2 do work - get back errors like "Cache not found" on gets and sets because can't create it)
- running with debug flags `GRPC_VERBOSITY=DEBUG GRPC_TRACE=all` ([Actions output](GRPC_VERBOSITY=DEBUG GRPC_TRACE=all))
    - this indicated it's not a DNS problem - was able to successfully resolve IP addresses
- running with debug flag `NODE_DEBUG=http2`
    - this indicated the issue seems to be that the socket gets closed ([Actions output](https://github.com/momentohq/client-sdk-javascript/runs/5668388937?check_suite_focus=true))
```
HTTP2 1796: Http2Session client: setting up session handle
HTTP2 1796: Http2Session client: sending settings
HTTP2 1796: Http2Session client: submitting settings
HTTP2 1796: Http2Session client: setting up session handle
HTTP2 1796: Http2Session client: sending settings
HTTP2 1796: Http2Session client: submitting settings
HTTP2 1796: Http2Session client: settings received
HTTP2 1796: Http2Session client: socket closed
HTTP2 1796: Http2Session client: marking session closed
HTTP2 1796: Http2Session client: submitting goaway
HTTP2 1796: Http2Session client: destroying
HTTP2 1796: Http2Session client: start closing/destroying undefined
HTTP2 1796: Http2Session client: finishSessionClose
HTTP2 1796: Http2Session client: settings received
HTTP2 1745: Http2Session client: marking session closed
HTTP2 1745: Http2Session client: submitting goaway
HTTP2 1745: Http2Session client: destroying
HTTP2 1745: Http2Session client: start closing/destroying undefined
HTTP2 1745: Http2Session client: finishSessionClose
HTTP2 1745: Http2Session client: finishSessionClose socket end undefined undefined
HTTP2 1745: Http2Stream 1 [Http2Session client]: closed with code 8, closed true, readable true
HTTP2 1745: Http2Stream 1 [Http2Session client]: destroying stream
```

vs. locally:

```
HTTP2 4721: Http2Session client: setting up session handle
HTTP2 4721: Http2Session client: sending settings
HTTP2 4721: Http2Session client: submitting settings
HTTP2 4721: Http2Session client: initiating request
HTTP2 4721: Http2Session client: connected, initializing request
HTTP2 4721: Http2Stream 1 [Http2Session client]: shutting down writable on last write
HTTP2 4721: Http2Stream 1 [Http2Session client]: shutting down writable on _final
HTTP2 4721: Http2Stream 1 [Http2Session client]: shutdownWritable() already called
HTTP2 4721: Http2Session client: setting up session handle
HTTP2 4721: Http2Session client: sending settings
HTTP2 4721: Http2Session client: submitting settings
HTTP2 4721: Http2Session client: setting up session handle
HTTP2 4721: Http2Session client: sending settings
HTTP2 4721: Http2Session client: submitting settings
HTTP2 4721: Http2Session client: settings received
HTTP2 4721: Http2Stream 1 [Http2Session client]: headers received
HTTP2 4721: Http2Stream 1 [Http2Session client]: emitting stream 'response' event
HTTP2 4721: Http2Session client: settings received
HTTP2 4721: Http2Session client: settings received
HTTP2 4721: Http2Stream 1 [Http2Session client]: headers received
HTTP2 4721: Http2Stream 1 [Http2Session client]: emitting stream 'trailers' event
HTTP2 4721: Http2Stream 1 [Http2Session client]: closed with code 0, closed true, readable false
HTTP2 4721: Http2Stream 1 [Http2Session client]: destroying stream
```

Steps for debugging
- [x] run in Lambda (could just write simple thing that uses SDK to call `momento.createCache`)
- [x] run in EC2
- [x] run with Docker

(For these cases it might be worth running just one single test - e.g. comment out everything but https://github.com/momentohq/client-sdk-javascript/blob/6cb95d8ad4ef1ccde4a7232dd514e9797acd8610/integration/SimpleCacheClient.test.ts#L47-L55)

None of these reproduced the problem :sob: - see comments below from @poppoerika. 

Other debugging ideas:
- [ ] try using `grpc` rather than `grpc-js`
- [ ] add NLB access logging for control plane (https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-access-logs.html) (@virratanasangpunth )
- [ ] if we want to go this far... could try setting up a simple static self-hosted runner with no egress proxy (e.g. bare EC2 image with docker and the GH runner agent on it)
- [ ] submit issue to GitHub Actions support asking what might be special about actions environment (egress proxy?)
- [ ] submit issue to grpc-js with debugging info

**Comment by mjindalmotiv8** [comment]
We might have to try this in a dev cell or against prod - alpha mr2 is currently unstable so we should not use that

**Comment by danielamiao** [comment]
@bruuuuuuuce what are the `grpc-js` issues you are following that have similar symptoms?

**Comment by mjindalmotiv8** [comment]
@poppoerika - Please run the integ tests in a loop and have them run after like a 10 minutes interval (because we want the GRPC channels to be teared down). We should also try to run them in a container.

**Comment by poppoerika** [comment]
Running on a Lambda node v.14.x - Create, set, get cache succeeded.
```
START RequestId: 6596bb29-7ce8-429a-871b-5a2a37a630ec Version: $LATEST
2022-03-24T18:58:26.996Z	6596bb29-7ce8-429a-871b-5a2a37a630ec	INFO	Hello
2022-03-24T18:58:27.550Z	6596bb29-7ce8-429a-871b-5a2a37a630ec	INFO	Storing key=key, value=value, ttl=60
2022-03-24T18:58:27.729Z	6596bb29-7ce8-429a-871b-5a2a37a630ec	INFO	cache hit: value
END RequestId: 6596bb29-7ce8-429a-871b-5a2a37a630ec
REPORT RequestId: 6596bb29-7ce8-429a-871b-5a2a37a630ec	Duration: 754.37 ms	Billed Duration: 755 ms	Memory Size: 128 MB	Max Memory Used: 69 MB	Init Duration: 316.13 ms
```

**Comment by poppoerika** [comment]
Running the integration test in a Docker container (node v16.5.0) succeeded.
```
client-sdk-javascript [chore/testingActions●] % docker run js-debug    

> @momento/sdk@0.0.1 integration
> jest --config jest-integration.config.js

PASS integration/SimpleCacheClient.test.ts
  SimpleCacheClient.ts Integration Tests
    ✓ should create and delete a cache (1285 ms)
    ✓ should throw CacheNotFoundError if deleting a non-existent cache (121 ms)
    ✓ should throw CacheAlreadyExistsError if trying to create a cache that already exists (95 ms)

Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        2.81 s
Ran all test suites.
```

**Comment by poppoerika** [comment]
> Please run the integ tests in a loop and have them run after like a 10 minutes interval (because we want the GRPC channels to be teared down). We should also try to run them in a container.

So far, three loops have completed (10 minutes apart), and all of them have been successful.

**Comment by rlinehan** [comment]
Another Actions run with a higher timeout resulted in `ended with status: code=14 details="Connection dropped"` ([Actions output](https://github.com/momentohq/client-sdk-javascript/runs/5683837593?check_suite_focus=true)).

**Comment by poppoerika** [comment]
We updated `@grpc/grpc-js` version to the latest, `v.1.5.10` for the JS SDK as well as our client protos.
Now the integration tests successfully passed on GitHub Action.

**Comment by rlinehan** [comment]
The fix only seems to have worked on Mac OS runners - it's still breaking on Ubuntu 😭 ([Actions run output](https://github.com/momentohq/client-sdk-javascript/runs/5687080970?check_suite_focus=true)).
