### ISSUE TITLE
update nodejs/.net observability docs re: logging and new metrics

### ISSUE THREAD

**Issue by cprice404** [momentohq/client-sdk-javascript#586]
Three things to hit here:

- [x] In observability docs for nodejs: add an example of how to increase the logging level so users know how to see debug logs.
- [x] In observability docs for nodejs: describe experimentalmetrics middleware. probably above otel stuff.
- [x] In observability docs for .NET: describe experimentalmetrics middleware.

**Comment by anitarua** [comment]
Will also mention the new cloudwatch metrics example in nodejs repo
