### ISSUE TITLE
Remove CacheRole.None and TopicRole.None

### ISSUE THREAD

**Issue by danielamiao** [momentohq/client-sdk-javascript#618]
We don't support deny permissions today so `CacheRole.None` and `TopicRole.None` are not supported and should not be exposed in the SDK. We keep it in the proto because the default enum (0) needs to exist.

**Comment by krispraws** [comment]
Done in https://github.com/momentohq/client-sdk-javascript/pull/598

**Comment by krispraws** [comment]
Released in momento js sdk 1.27.2
