### ISSUE TITLE
proposal of modification Step4

### ISSUE THREAD

**Issue by MomentoBigFun** [momentohq/client-sdk-javascript#834]
Step may need more explanation how to modify wrangler.toml. 
Below is my idea.

Cloudflare uses a file called wrangler.toml to configure the development and publishing of a worker. More information about Cloudflare configuration can be found on their website. In the example directory, update the wrangler.toml file with the cache name and HTTP endpoint as they appeared in the Momento Console. And also, you need to wave `#` from blow 3 lines.
[vars]
MOMENTO_REST_ENDPOINT =
MOMENTO_CACHE_NAME =

**Comment by cprice404** [comment]
Thanks for the feedback @MomentoBigFun !

@pratik151192 I think this might be similar to what you did in your recent PR, can you weigh in if you get a moment?

**Comment by pratik151192** [comment]
Hey @MomentoBigFun, thanks for calling this out! We have updated our README to be more explicit here https://github.com/momentohq/client-sdk-javascript/pull/944. Feel free to re-open this issue if you see something else missing! Thanks again!
