### ISSUE TITLE
Fix tests leaking caches

### ISSUE THREAD

**Issue by kvcache** [momentohq/client-sdk-javascript#947]
```
RESOURCE_EXHAUSTED: Your account has a limit of 10 caches. Please contact support if your use case necessitates more caches.
```

Repeatedly running the integration tests in this client sdk results in caches leaking over time until an account limit is reached. Once this happens, the tests can't run anymore.

**Comment by pratik151192** [comment]
This was addressed here https://github.com/momentohq/canaries-kitchensink/pull/23 @kvcache
